name: Robot Tests and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install robotframework robotframework-seleniumlibrary

      - name: Prepare build directory
        run: |
          mkdir -p ./build
          cp -r ./* ./build/ 2>/dev/null || true
          rm -rf ./build/build  # Prevent nested directories

      - name: Start local server
        run: |
          python3 -m http.server 8000 --directory build &
          echo "SERVER_PID=$!" >> $GITHUB_ENV
          sleep 2  # Give the server a moment to start

      - name: Run Robot tests
        run: |
          export URL=http://localhost:8000
          robot tests/ || exit 1

      - name: Stop local server
        if: always()
        run: |
          if [ ! -z "$SERVER_PID" ]; then
            kill $SERVER_PID || true
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          keep_files: false
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}